<?php
declare(strict_types=1);

use App\Core\DateFormatter;
use App\Core\Url;

function e_admin_dashboard(string $v): string { return htmlspecialchars($v, ENT_QUOTES, 'UTF-8'); }
$title='Administration — Tech4U-QUEST';
$activePage='dashboard';
require __DIR__.'/_header.php';
?>
<div class="page-head"><div><span class="eyebrow">⚙️ ADMINISTRATION</span><h1>Tableau de bord</h1><p>Connecté en tant que <?= e_admin_dashboard((string)$admin['login']) ?> · Année scolaire <?= e_admin_dashboard($schoolYear) ?></p></div><div style="display:flex;gap:.75rem;flex-wrap:wrap"><a class="btn btn-secondary" href="<?= e_admin_dashboard(Url::to()) ?>">Voir le site</a><a class="btn btn-danger" href="<?= e_admin_dashboard(Url::to('logout')) ?>">Déconnexion</a></div></div>
<section class="grid kpi-grid"><div class="card kpi"><span>Élèves actifs</span><strong><?= $stats['students'] ?></strong><small><?= $stats['classes'] ?> classe(s)</small></div><div class="card kpi"><span>Modules</span><strong><?= $stats['modules'] ?></strong><small><?= $stats['categories'] ?> catégories</small></div><div class="card kpi"><span>Questions actives</span><strong><?= $stats['questions'] ?></strong><small>cible initiale : 330</small></div><div class="card kpi"><span>Tentatives</span><strong><?= $stats['attempts'] ?></strong><small><?= $stats['awarded_badges'] ?> badge(s) attribué(s)</small></div></section>
<section class="card" style="padding:1.25rem;margin-top:1rem"><div style="display:flex;justify-content:space-between;align-items:flex-start;gap:1rem;flex-wrap:wrap"><div><h2 style="margin:0">État de préparation du site</h2><p>Les éléments ci-dessous doivent être configurés avant l’ouverture aux élèves.</p></div><div style="display:flex;gap:.5rem;flex-wrap:wrap"><a class="btn btn-primary" href="<?= e_admin_dashboard(Url::to('admin/questions')) ?>">Gérer les questions</a><a class="btn btn-secondary" href="<?= e_admin_dashboard(Url::to('admin/students')) ?>">Importer les élèves CSV</a></div></div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:1rem;margin-top:1rem"><?php foreach($configItems as $item): ?><a class="card" href="<?= e_admin_dashboard($item['url']) ?>" style="padding:1rem;text-decoration:none;color:inherit;border-color:<?= $item['ok']?'#2dd4bf':'#f59e0b' ?>"><div style="display:flex;justify-content:space-between;gap:.75rem"><strong><?= e_admin_dashboard($item['title']) ?></strong><span><?= $item['ok']?'✅':'⚠️' ?></span></div><p style="margin:.5rem 0 0"><?= e_admin_dashboard($item['detail']) ?></p></a><?php endforeach; ?></div></section>
<section class="card table-card" style="margin-top:1rem"><div class="card-pad"><div style="display:flex;justify-content:space-between;gap:1rem;align-items:center;flex-wrap:wrap"><div><h2 style="margin:0">Configuration des modules</h2><p style="margin:.35rem 0 0">Contrôle des quotas et de la couverture de la banque de questions.</p></div><a class="btn btn-secondary" href="<?= e_admin_dashboard(Url::to('admin/modules')) ?>">Configurer</a></div></div><div style="overflow:auto"><table class="table"><thead><tr><th>Module</th><th>Catégories</th><th>Questions/tentative</th><th>Quotas</th><th>Vies</th><th>Banque</th><th>État</th></tr></thead><tbody><?php foreach($moduleStatus as $module): $quotaOk=(int)$module['configured_quota']===(int)$module['question_count']; $bankOk=(int)$module['active_questions']>=(int)$module['question_count']; $ok=$quotaOk&&$bankOk&&(int)$module['categories']>0; ?><tr><td><?= e_admin_dashboard((string)($module['icon']?:'📘')) ?> <strong><?= e_admin_dashboard((string)$module['title']) ?></strong></td><td><?= (int)$module['categories'] ?></td><td><?= (int)$module['question_count'] ?></td><td><?= (int)$module['configured_quota'] ?>/<?= (int)$module['question_count'] ?></td><td><?= (int)$module['initial_lives'] ?></td><td><?= (int)$module['active_questions'] ?>/<?= (int)$module['recommended_bank_size'] ?></td><td><span class="badge"><?= $ok?'Prêt':'À compléter' ?></span></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="card table-card" style="margin-top:1rem"><div class="card-pad"><h2 style="margin:0">Activité récente</h2></div><div style="overflow:auto"><table class="table"><thead><tr><th>Élève</th><th>Module</th><th>Score</th><th>État</th><th>Date</th></tr></thead><tbody><?php if(!$recent): ?><tr><td colspan="5">Aucune tentative pour le moment.</td></tr><?php endif; ?><?php foreach($recent as $attempt): ?><tr><td><code><?= e_admin_dashboard((string)$attempt['login_code']) ?></code></td><td><?= e_admin_dashboard((string)$attempt['module_title']) ?></td><td><?= (int)$attempt['score'] ?>/<?= (int)$attempt['total_questions'] ?></td><td><span class="badge"><?= e_admin_dashboard((string)$attempt['status']) ?></span></td><td><?= e_admin_dashboard(DateFormatter::human((string)$attempt['started_at'])) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php require __DIR__.'/_footer.php'; ?>
