<?php
declare(strict_types=1);
use App\Core\Auth;
function e_admin_modules(string $v): string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
$title='Modules — Administration Tech4U-QUEST';$activePage='modules';require __DIR__.'/_header.php';
?>
<div class="page-head"><div><span class="eyebrow">🧭 CONFIGURATION PÉDAGOGIQUE</span><h1>Modules et réglages</h1><p>Active uniquement les modules déjà traités en classe, puis règle les questions, les vies et les quotas par catégorie.</p></div></div>
<?php if($message):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#2dd4bf"><strong><?=e_admin_modules($message)?></strong></div><?php endif;?>
<?php if($error):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#fb7185"><strong><?=e_admin_modules($error)?></strong></div><?php endif;?>
<?php foreach($modules as $module): $categories=$module['categories'];$target=max(1,(int)$module['recommended_bank_size']);$percent=min(100,(int)round(((int)$module['active_questions']/$target)*100));$quotaTotal=array_sum(array_map(static fn(array $c):int=>(int)$c['draw_count'],$categories));$isActive=(int)$module['active']===1;?>
<section class="card" style="padding:1.25rem;margin-bottom:1rem;<?= $isActive?'':'opacity:.78;' ?>"><div style="display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap;align-items:flex-start"><div><span class="eyebrow"><?=e_admin_modules((string)($module['icon']?:'📘'))?> MODULE <?= (int)$module['id']?></span><h2 style="margin:.35rem 0"><?=e_admin_modules((string)$module['title'])?></h2><p><?=e_admin_modules((string)($module['description']??''))?></p></div><div style="display:flex;gap:.5rem;align-items:center;flex-wrap:wrap"><span class="chip"><?= $isActive?'🟢 Visible aux élèves':'🔴 Masqué aux élèves' ?></span><span class="chip"><?= (int)$module['active_questions']?> / <?= (int)$module['recommended_bank_size']?> questions</span></div></div><div class="progress" style="margin:.8rem 0 1.25rem"><span style="width:<?=$percent?>%"></span></div>
<form method="post" class="module-config-form"><input type="hidden" name="csrf_token" value="<?=e_admin_modules(Auth::csrfToken())?>"><input type="hidden" name="module_id" value="<?= (int)$module['id']?>"><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1rem;margin-bottom:1rem"><div class="form-group"><label class="label">Disponibilité élèves</label><label><input type="checkbox" name="module_active" value="1" <?=$isActive?'checked':''?>> <strong>Module actif</strong></label></div><div class="form-group"><label class="label">Questions par tentative</label><input class="input question-total" type="number" value="<?=$quotaTotal?>" readonly></div><div class="form-group"><label class="label">Vies initiales</label><input class="input" type="number" min="1" max="20" name="initial_lives" value="<?= (int)$module['initial_lives']?>" required></div><div class="form-group"><label class="label">Badge</label><label><input type="checkbox" name="badge_enabled" value="1" <?= (int)$module['badge_enabled']===1?'checked':''?>> <?=e_admin_modules((string)(($module['badge_icon']??'').' '.($module['badge_name']??'')))?></label></div></div>
<div style="overflow:auto"><table class="table"><thead><tr><th>Catégorie</th><th>Questions actives</th><th>Cible banque</th><th>Quota</th><th>État</th></tr></thead><tbody><?php foreach($categories as $category):$enough=(int)$category['active_questions']>=(int)$category['draw_count'];?><tr><td><strong><?=e_admin_modules((string)$category['name'])?></strong><br><small><?=e_admin_modules((string)($category['description']??''))?></small></td><td><?= (int)$category['active_questions']?></td><td><?= (int)$category['recommended_bank_size']?></td><td><input class="input category-quota" style="max-width:100px" type="number" min="0" max="100" name="category_count[<?= (int)$category['id']?>]" value="<?= (int)$category['draw_count']?>" required></td><td><span class="badge"><?=$enough?'OK':'À compléter'?></span></td></tr><?php endforeach;?></tbody></table></div><div style="margin-top:1rem"><button class="btn btn-primary" type="submit">Enregistrer la configuration</button></div></form></section><?php endforeach;?>
<script>document.querySelectorAll('.module-config-form').forEach(form=>{const total=form.querySelector('.question-total'),qs=form.querySelectorAll('.category-quota');const refresh=()=>{let s=0;qs.forEach(i=>{const v=parseInt(i.value,10);if(!Number.isNaN(v)&&v>0)s+=v});total.value=s};qs.forEach(i=>i.addEventListener('input',refresh));refresh();});</script>
<?php require __DIR__.'/_footer.php';?>
