<?php
declare(strict_types=1);
use App\Core\Auth;use App\Core\Url;
function e_admin_students(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
$title='Élèves — Administration Tech4U-QUEST';$activePage='students';require __DIR__.'/_header.php';
?>
<div class="page-head"><div><span class="eyebrow">👥 GESTION DES ÉLÈVES</span><h1>Élèves</h1><p>Synchronisation avec les identifiants stables provenant de la base MySQL locale.</p></div><a class="btn btn-secondary" href="<?=e_admin_students(Url::to('admin/students/template'))?>">Télécharger le modèle CSV</a></div>
<?php if($message):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#2dd4bf"><strong><?=e_admin_students($message)?></strong></div><?php endif;?><?php if($error):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#fb7185"><strong><?=e_admin_students($error)?></strong></div><?php endif;?>
<?php if($importResult&&!empty($importResult['errors'])):?><div class="card" style="padding:1rem;margin-bottom:1rem"><h3>Lignes non importées</h3><ul><?php foreach($importResult['errors'] as $er):?><li><?=e_admin_students((string)$er)?></li><?php endforeach;?></ul></div><?php endif;?>
<section class="grid kpi-grid"><div class="card kpi"><span>Élèves</span><strong><?= (int)$totals['total']?></strong></div><div class="card kpi"><span>Actifs</span><strong><?= (int)$totals['active']?></strong></div><div class="card kpi"><span>Classes</span><strong><?=count($classes)?></strong></div><div class="card kpi"><span>Mot de passe à changer</span><strong><?= (int)$totals['must_change']?></strong></div></section>
<section class="card" style="padding:1.25rem;margin-top:1rem;border-color:#8b5cf6"><div style="display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap"><div><span class="eyebrow">🧪 COMPTE DE PRÉSENTATION</span><h2>Compte inspecteurs</h2><?php if($demoStudent):?><p>Login : <code><?=e_admin_students((string)$demoStudent['login_code'])?></code> · Tentatives : <?= (int)$demoStudent['attempts']?> · Badges : <?= (int)$demoStudent['badges']?></p><?php else:?><p>Le compte DEMO-1 n’existe pas encore.</p><?php endif;?></div><?php if($demoStudent):?><form method="post" onsubmit="return confirm('Réinitialiser DEMO-1 ?');"><input type="hidden" name="csrf_token" value="<?=e_admin_students(Auth::csrfToken())?>"><input type="hidden" name="action" value="reset_demo"><button class="btn btn-danger">↻ Réinitialiser DEMO-1</button></form><?php endif;?></div></section>
<section class="card" style="padding:1.25rem;margin-top:1rem"><h2>Importer / mettre à jour une liste CSV</h2><p>Colonnes : <code>id;class_code;student_number;password;active;must_change_password</code>.</p><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=e_admin_students(Auth::csrfToken())?>"><div class="form-group"><label class="label" for="csv">Fichier CSV (2 Mo maximum)</label><input class="input" type="file" id="csv" name="csv" accept=".csv,text/csv,text/plain" required></div><button class="btn btn-primary">Importer et synchroniser</button></form></section>
<section class="card table-card" style="margin-top:1rem"><div class="card-pad"><div style="display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap"><h2 style="margin:0">Liste actuelle</h2><form method="get" style="display:flex;gap:.5rem"><select class="input" name="class"><option value="">Toutes les classes</option><?php foreach($classes as $c):?><option value="<?=e_admin_students((string)$c['class_code'])?>" <?=$filterClass===(string)$c['class_code']?'selected':''?>><?=e_admin_students((string)$c['class_code'])?> (<?= (int)$c['total']?>)</option><?php endforeach;?></select><button class="btn btn-secondary">Filtrer</button></form></div></div><div style="overflow:auto"><table class="table"><thead><tr><th>ID MySQL</th><th>Classe</th><th>N°</th><th>Login</th><th>État</th><th>Mot de passe</th><th>Mise à jour</th></tr></thead><tbody><?php if(!$students):?><tr><td colspan="7">Aucun élève enregistré.</td></tr><?php endif;?><?php foreach($students as $s):?><tr><td><?= (int)$s['id']?></td><td><?=e_admin_students((string)$s['class_code'])?></td><td><?= (int)$s['student_number']?></td><td><code><?=e_admin_students((string)$s['login_code'])?></code></td><td><span class="badge"><?= (int)$s['active']===1?'Actif':'Inactif'?></span></td><td><?= (int)$s['must_change_password']===1?'À changer':'Défini'?></td><td><?=e_admin_students((string)($s['updated_at']?:$s['created_at']))?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require __DIR__.'/_footer.php';?>
