<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/app/Core/Database.php';
require_once dirname(__DIR__,2).'/app/Core/Auth.php';
require_once dirname(__DIR__,2).'/app/Services/QuestionBankService.php';
use App\Core\Auth; use App\Core\Database; use App\Services\QuestionBankService;
$admin=Auth::requireAdmin('../login.php'); $db=Database::connection(); $svc=new QuestionBankService($db);
function e(string $v): string { return htmlspecialchars($v,ENT_QUOTES,'UTF-8'); }
$message=$error=null;
if ($_SERVER['REQUEST_METHOD']==='POST') {
 if (!Auth::validateCsrf($_POST['csrf_token']??null)) $error='Jeton de sécurité invalide.';
 else try {
  $id=(int)($_POST['id']??0); $action=$_POST['action']??'';
  if ($action==='toggle') { $svc->toggle($id); $message='État de la question modifié.'; }
  elseif ($action==='duplicate') { $new=$svc->duplicate($id); $message='Question dupliquée (#'.$new.').'; }
 } catch(Throwable $ex){$error=$ex->getMessage();}
}
$moduleId=(int)($_GET['module_id']??0); $categoryId=(int)($_GET['category_id']??0); $type=trim((string)($_GET['type']??'')); $q=trim((string)($_GET['q']??'')); $active=(string)($_GET['active']??''); $group=trim((string)($_GET['group']??''));
$modules=$db->query('SELECT id,title FROM modules ORDER BY display_order,id')->fetchAll(PDO::FETCH_ASSOC);
$categories=$db->query('SELECT id,module_id,name FROM categories ORDER BY module_id,display_order,id')->fetchAll(PDO::FETCH_ASSOC);
$groups=$db->query('SELECT DISTINCT exclusion_group FROM questions WHERE exclusion_group IS NOT NULL AND trim(exclusion_group)<>"" ORDER BY exclusion_group')->fetchAll(PDO::FETCH_COLUMN);
$sql='SELECT q.id,q.question,q.type,q.difficulty,q.lesson,q.topic,q.active,q.exclusion_group,c.name category_name,m.title module_title,(SELECT COUNT(*) FROM question_answers a WHERE a.question_id=q.id) answer_count FROM questions q JOIN categories c ON c.id=q.category_id JOIN modules m ON m.id=c.module_id WHERE 1=1'; $p=[];
if($moduleId){$sql.=' AND m.id=:m';$p['m']=$moduleId;} if($categoryId){$sql.=' AND c.id=:c';$p['c']=$categoryId;} if(in_array($type,['qcm','true_false','multiple','short'],true)){$sql.=' AND q.type=:t';$p['t']=$type;} if($q!==''){$sql.=' AND q.question LIKE :q';$p['q']='%'.$q.'%';} if($active==='1'||$active==='0'){$sql.=' AND q.active=:a';$p['a']=(int)$active;} if($group!==''){$sql.=' AND q.exclusion_group=:g';$p['g']=$group;} $sql.=' ORDER BY q.id DESC LIMIT 500';
$stmt=$db->prepare($sql);$stmt->execute($p);$rows=$stmt->fetchAll(PDO::FETCH_ASSOC);
$activePage='questions.php';
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Questions — Tech4U-QUEST</title><link rel="stylesheet" href="../assets/css/app.css"></head><body><div class="admin-shell"><?php require __DIR__.'/_sidebar.php'; ?><main class="admin-main"><div class="page-head"><div><span class="eyebrow">❓ BANQUE DE QUESTIONS</span><h1>Questions</h1><p>Ajout, correction, filtrage, import, export et groupes d’exclusion.</p></div><div style="display:flex;gap:.6rem;flex-wrap:wrap"><a class="btn btn-primary" href="question-edit.php">+ Ajouter</a><a class="btn btn-secondary" href="question-exclusions.php">🔀 Groupes d’exclusion</a><a class="btn btn-secondary" href="questions-import.php">Importer CSV</a><a class="btn btn-secondary" href="questions-export.php">Exporter CSV</a><a class="btn btn-secondary" href="questions-reference.php">Référentiel</a></div></div>
<?php if($message):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#2dd4bf"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#fb7185"><?=e($error)?></div><?php endif;?>
<section class="card" style="padding:1rem;margin-bottom:1rem"><form method="get" class="grid" style="grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.75rem"><select class="input" name="module_id"><option value="0">Tous les modules</option><?php foreach($modules as $m):?><option value="<?=$m['id']?>" <?=$moduleId===$m['id']?'selected':''?>><?=e($m['title'])?></option><?php endforeach;?></select><select class="input" name="category_id"><option value="0">Toutes les catégories</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>" <?=$categoryId===$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select><select class="input" name="type"><option value="">Tous les types</option><?php foreach(['qcm','true_false','multiple','short'] as $t):?><option <?=$type===$t?'selected':''?>><?=$t?></option><?php endforeach;?></select><select class="input" name="group"><option value="">Tous les groupes</option><?php foreach($groups as $g):?><option value="<?=e((string)$g)?>" <?=$group===(string)$g?'selected':''?>><?=e((string)$g)?></option><?php endforeach;?></select><select class="input" name="active"><option value="">Tous les états</option><option value="1" <?=$active==='1'?'selected':''?>>Actives</option><option value="0" <?=$active==='0'?'selected':''?>>Inactives</option></select><input class="input" name="q" value="<?=e($q)?>" placeholder="Rechercher une question"><button class="btn btn-primary">Filtrer</button></form></section>
<section class="card table-card"><div style="overflow:auto"><table class="table"><thead><tr><th>ID</th><th>Module / catégorie</th><th>Question</th><th>Groupe d’exclusion</th><th>Type</th><th>Niveau</th><th>Réponses</th><th>État</th><th>Actions</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="9">Aucune question.</td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td>#<?=$r['id']?></td><td><small><?=e($r['module_title'])?></small><br><strong><?=e($r['category_name'])?></strong></td><td><?=nl2br(e($r['question']))?><br><small><?=e((string)$r['lesson'])?> <?=e((string)$r['topic'])?></small></td><td><?php if(trim((string)($r['exclusion_group']??''))!==''):?><span class="badge"><?=e((string)$r['exclusion_group'])?></span><?php else:?><small>—</small><?php endif;?></td><td><?=$r['type']?></td><td><?=$r['difficulty']?>/5</td><td><?=$r['answer_count']?></td><td><span class="badge"><?=$r['active']?'Active':'Inactive'?></span></td><td style="white-space:nowrap"><a class="btn btn-secondary" href="question-edit.php?id=<?=$r['id']?>">Modifier</a><form method="post" style="display:inline"><input type="hidden" name="csrf_token" value="<?=e(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-secondary" name="action" value="duplicate">Dupliquer</button><button class="btn btn-secondary" name="action" value="toggle"><?=$r['active']?'Désactiver':'Activer'?></button></form></td></tr><?php endforeach;?></tbody></table></div></section></main></div></body></html>