<?php
declare(strict_types=1);
use App\Core\Auth;use App\Core\Url;
function e_admin_edit(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
$title=($id?'Modifier':'Ajouter').' une question';$activePage='questions';require dirname(__DIR__).'/_header.php';
?>
<div class="page-head"><div><span class="eyebrow">❓ BANQUE DE QUESTIONS</span><h1><?= $id?'Modifier la question #'.$id:'Ajouter une question'?></h1></div><a class="btn btn-secondary" href="<?=e_admin_edit(Url::to('admin/questions'))?>">Retour</a></div>
<?php if($error):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#fb7185"><?=e_admin_edit($error)?></div><?php endif;?>
<form method="post" class="card" style="padding:1.25rem"><input type="hidden" name="csrf_token" value="<?=e_admin_edit(Auth::csrfToken())?>"><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1rem"><div class="form-group"><label class="label">Catégorie</label><select class="input" name="category_id" required><option value="">Choisir</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>" <?=(string)$question['category_id']===(string)$c['id']?'selected':''?>><?=e_admin_edit((string)$c['module_title'].' — '.(string)$c['name'])?></option><?php endforeach;?></select></div><div class="form-group"><label class="label">Type</label><select class="input" name="type"><?php foreach(['qcm','true_false','multiple','short'] as $t):?><option value="<?=$t?>" <?=$question['type']===$t?'selected':''?>><?=$t?></option><?php endforeach;?></select></div><div class="form-group"><label class="label">Difficulté</label><input class="input" type="number" min="1" max="5" name="difficulty" value="<?=e_admin_edit((string)$question['difficulty'])?>"></div></div><div class="form-group"><label class="label">Question</label><textarea class="input" name="question" rows="4" required><?=e_admin_edit((string)$question['question'])?></textarea></div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1rem"><div class="form-group"><label class="label">Leçon</label><input class="input" name="lesson" value="<?=e_admin_edit((string)$question['lesson'])?>"></div><div class="form-group"><label class="label">Sujet</label><input class="input" name="topic" value="<?=e_admin_edit((string)$question['topic'])?>"></div><div class="form-group"><label class="label">Groupe d’exclusion</label><input class="input" name="exclusion_group" maxlength="50" value="<?=e_admin_edit((string)($question['exclusion_group']??''))?>" placeholder="ex. ascii-cat"></div></div><div class="form-group"><label class="label">Explication pédagogique</label><textarea class="input" name="explanation" rows="3"><?=e_admin_edit((string)$question['explanation'])?></textarea></div><h2>Réponses</h2><p><small>QCM : 1 bonne réponse. Multiple : plusieurs possibles. Vrai/Faux : 2 réponses. Short : variantes acceptées.</small></p><?php for($i=0;$i<max(6,count($answers));$i++):$a=$answers[$i]??['answer'=>'','is_correct'=>0];?><div style="display:grid;grid-template-columns:auto 1fr;gap:.75rem;align-items:center;margin:.5rem 0"><label><input type="checkbox" name="correct[<?=$i?>]" value="1" <?=!empty($a['is_correct'])?'checked':''?>> Correcte</label><input class="input" name="answer[<?=$i?>]" value="<?=e_admin_edit((string)$a['answer'])?>" placeholder="Réponse <?=($i+1)?>"></div><?php endfor;?><label style="display:flex;gap:.5rem;align-items:center;margin:1rem 0"><input type="checkbox" name="active" value="1" <?=!empty($question['active'])?'checked':''?>> Question active</label><button class="btn btn-primary" type="submit">Enregistrer</button></form>
<?php require dirname(__DIR__).'/_footer.php';?>
