<?php
declare(strict_types=1);
use App\Core\Auth;use App\Core\Url;
function e_admin_excl(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
$title='Exclusions de questions — Tech4U-QUEST';$activePage='exclusions';require dirname(__DIR__).'/_header.php';
?>
<div class="page-head"><div><span class="eyebrow">🔀 EXCLUSIONS</span><h1>Questions incompatibles</h1><p>Donne le même groupe aux questions qui ne doivent jamais apparaître ensemble dans une même tentative.</p></div><a class="btn btn-secondary" href="<?=e_admin_excl(Url::to('admin/questions'))?>">Retour aux questions</a></div>
<?php if($message):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#2dd4bf"><?=e_admin_excl($message)?></div><?php endif;?><?php if($error):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#fb7185"><?=e_admin_excl($error)?></div><?php endif;?>
<form method="get" class="card" style="padding:1rem;margin-bottom:1rem"><div class="grid" style="grid-template-columns:1fr 1fr auto;gap:.75rem"><select class="input" name="module"><option value="0">Tous les modules</option><?php foreach($modules as $m):?><option value="<?=$m['id']?>" <?=$module===(int)$m['id']?'selected':''?>><?=e_admin_excl((string)$m['title'])?></option><?php endforeach;?></select><select class="input" name="category"><option value="0">Toutes les catégories</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>" <?=$category===(int)$c['id']?'selected':''?>><?=e_admin_excl((string)$c['module_title'].' — '.(string)$c['name'])?></option><?php endforeach;?></select><button class="btn btn-secondary">Filtrer</button></div></form>
<form method="post"><input type="hidden" name="csrf_token" value="<?=e_admin_excl(Auth::csrfToken())?>"><div class="card" style="overflow:auto"><table class="table"><thead><tr><th>ID</th><th>Module / catégorie</th><th>Question</th><th>Groupe d’exclusion</th></tr></thead><tbody><?php foreach($questions as $q):?><tr><td>#<?=$q['id']?></td><td><small><?=e_admin_excl((string)$q['module_title'])?><br><?=e_admin_excl((string)$q['category_name'])?></small></td><td style="min-width:360px;white-space:pre-wrap"><?=e_admin_excl((string)$q['question'])?></td><td><input class="input" style="min-width:180px" name="group[<?=$q['id']?>]" value="<?=e_admin_excl((string)($q['exclusion_group']??''))?>" placeholder="ex. ascii-cat"></td></tr><?php endforeach;?></tbody></table></div><div style="margin-top:1rem"><button class="btn btn-primary" type="submit">Enregistrer les groupes</button></div></form>
<?php require dirname(__DIR__).'/_footer.php';?>
