<?php
declare(strict_types=1);
use App\Core\Auth;use App\Core\Url;
function e_admin_excl(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
function excl_page_url(int $targetPage,int $module,int $category,string $search):string{
    $params=[];
    if($module>0)$params['module']=$module;
    if($category>0)$params['category']=$category;
    if($search!=='')$params['q']=$search;
    if($targetPage>1)$params['page']=$targetPage;
    $query=http_build_query($params);
    return Url::to('admin/questions/exclusions'.($query!==''?'?'.$query:''));
}
$title='Exclusions de questions — Tech4U-QUEST';$activePage='exclusions';require dirname(__DIR__).'/_header.php';
?>
<div class="page-head"><div><span class="eyebrow">🔀 EXCLUSIONS</span><h1>Questions incompatibles</h1><p>Donne le même groupe aux questions qui ne doivent jamais apparaître ensemble dans une même tentative.</p></div><a class="btn btn-secondary" href="<?=e_admin_excl(Url::to('admin/questions'))?>">Retour aux questions</a></div>
<?php if($message):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#2dd4bf"><?=e_admin_excl($message)?></div><?php endif;?><?php if($error):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#fb7185"><?=e_admin_excl($error)?></div><?php endif;?>
<form method="get" class="card" style="padding:1rem;margin-bottom:1rem"><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:.75rem"><select class="input" name="module"><option value="0">Tous les modules</option><?php foreach($modules as $m):?><option value="<?=$m['id']?>" <?=$module===(int)$m['id']?'selected':''?>><?=e_admin_excl((string)$m['title'])?></option><?php endforeach;?></select><select class="input" name="category"><option value="0">Toutes les catégories</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>" <?=$category===(int)$c['id']?'selected':''?>><?=e_admin_excl((string)$c['module_title'].' — '.(string)$c['name'])?></option><?php endforeach;?></select><input class="input" type="search" name="q" value="<?=e_admin_excl($search)?>" placeholder="Question ou groupe"><button class="btn btn-secondary">Filtrer</button><a class="btn btn-secondary" href="<?=e_admin_excl(Url::to('admin/questions/exclusions'))?>">Réinitialiser</a></div></form>
<div style="display:flex;justify-content:space-between;gap:1rem;align-items:center;flex-wrap:wrap;margin-bottom:.75rem"><strong><?=number_format((int)$totalRows,0,',',' ')?> question(s) active(s)</strong><span>Page <?= (int)$page?> / <?= (int)$totalPages?></span></div>
<form method="post"><input type="hidden" name="csrf_token" value="<?=e_admin_excl(Auth::csrfToken())?>"><div class="card" style="overflow:auto"><table class="table"><thead><tr><th>ID</th><th>Module / catégorie</th><th>Question</th><th>Groupe d’exclusion</th></tr></thead><tbody><?php if(!$questions):?><tr><td colspan="4">Aucune question active ne correspond aux filtres.</td></tr><?php endif;?><?php foreach($questions as $q):?><tr><td>#<?=$q['id']?></td><td><small><?=e_admin_excl((string)$q['module_title'])?><br><?=e_admin_excl((string)$q['category_name'])?></small></td><td style="min-width:360px;white-space:pre-wrap"><?=e_admin_excl((string)$q['question'])?></td><td><input class="input" style="min-width:180px" name="group[<?=$q['id']?>]" value="<?=e_admin_excl((string)($q['exclusion_group']??''))?>" placeholder="ex. ascii-cat"></td></tr><?php endforeach;?></tbody></table></div><?php if($questions):?><div style="margin-top:1rem"><button class="btn btn-primary" type="submit">Enregistrer cette page</button></div><?php endif;?></form>
<?php if($totalPages>1):?><nav aria-label="Pagination des exclusions" style="display:flex;gap:.4rem;flex-wrap:wrap;align-items:center;justify-content:center;margin-top:1.25rem"><?php if($page>1):?><a class="btn btn-secondary" href="<?=e_admin_excl(excl_page_url(1,$module,$category,$search))?>">« Première</a><a class="btn btn-secondary" href="<?=e_admin_excl(excl_page_url($page-1,$module,$category,$search))?>">‹ Précédente</a><?php endif;?><?php $start=max(1,$page-2);$end=min($totalPages,$page+2);for($p=$start;$p<=$end;$p++):?><a class="btn <?=$p===$page?'btn-primary':'btn-secondary'?>" href="<?=e_admin_excl(excl_page_url($p,$module,$category,$search))?>"><?=$p?></a><?php endfor;?><?php if($page<$totalPages):?><a class="btn btn-secondary" href="<?=e_admin_excl(excl_page_url($page+1,$module,$category,$search))?>">Suivante ›</a><a class="btn btn-secondary" href="<?=e_admin_excl(excl_page_url($totalPages,$module,$category,$search))?>">Dernière »</a><?php endif;?></nav><?php endif;?>
<?php require dirname(__DIR__).'/_footer.php';?>
