<?php
declare(strict_types=1);
use App\Core\Auth;use App\Core\Url;
function e_admin_import(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
$title='Import questions CSV — Tech4U-QUEST';$activePage='questions';require dirname(__DIR__).'/_header.php';
?>
<div class="page-head"><div><span class="eyebrow">📥 IMPORT CSV</span><h1>Importer des questions</h1><p>Analyse et prévisualisation avant insertion.</p></div><div class="page-actions"><a class="btn btn-secondary" href="<?=e_admin_import(Url::to('admin/questions'))?>">Retour</a><a class="btn btn-secondary" href="<?=e_admin_import(Url::to('admin/questions/template'))?>">Télécharger le modèle</a></div></div>
<?php if($message):?><div class="card notice notice-success"><?=e_admin_import($message)?></div><?php endif;?><?php foreach($errors as $er):?><div class="card notice notice-error"><?=e_admin_import((string)$er)?></div><?php endforeach;?>
<section class="card card-pad"><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=e_admin_import(Auth::csrfToken())?>"><input class="input" type="file" name="csv" accept=".csv,text/csv" required><div class="form-actions"><button class="btn btn-primary">Analyser le CSV</button></div></form></section>
<?php if(is_array($preview)):?><section class="card card-pad" style="margin-top:1rem"><h2>Prévisualisation</h2><p>✅ <?=count($preview['valid'])?> valides · ❌ <?=count($preview['errors'])?> erreur(s)</p><?php if($preview['errors']):?><div style="max-height:220px;overflow:auto"><?php foreach(array_slice($preview['errors'],0,100) as $er):?><p>❌ <?=e_admin_import((string)$er)?></p><?php endforeach;?></div><?php endif;?><?php if($preview['valid']):?><div class="table-scroll"><table class="table"><thead><tr><th>Catégorie</th><th>Question</th><th>Type</th><th>Difficulté</th><th>Groupe</th><th>Réponses</th></tr></thead><tbody><?php foreach(array_slice($preview['valid'],0,50) as $v):?><tr><td><?=$v['category_id']?></td><td><?=e_admin_import((string)$v['question'])?></td><td><?=e_admin_import((string)$v['type'])?></td><td><?=$v['difficulty']?></td><td><?=e_admin_import((string)($v['exclusion_group']??''))?></td><td><?=count($v['answers'])?></td></tr><?php endforeach;?></tbody></table></div><form method="post"><input type="hidden" name="csrf_token" value="<?=e_admin_import(Auth::csrfToken())?>"><div class="form-actions"><button class="btn btn-primary" name="action" value="commit">Importer les <?=count($preview['valid'])?> questions valides</button></div></form><?php endif;?></section><?php endif;?>
<?php require dirname(__DIR__).'/_footer.php';?>
