<?php
declare(strict_types=1);
use App\Core\Auth;
use App\Core\Url;
function e_admin_q(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
function question_page_url(int $targetPage): string
{
    $params = $_GET;
    unset($params['message'], $params['id']);
    $params['page'] = max(1, $targetPage);
    return Url::to('admin/questions?' . http_build_query($params));
}
$title='Questions — Tech4U-QUEST';$activePage='questions';require dirname(__DIR__).'/_header.php';
?>
<div class="page-head"><div><span class="eyebrow">❓ BANQUE DE QUESTIONS</span><h1>Questions</h1><p>Ajout, correction, filtrage, import, export et groupes d’exclusion.</p></div><div style="display:flex;gap:.6rem;flex-wrap:wrap"><a class="btn btn-primary" href="<?=e_admin_q(Url::to('admin/questions/new'))?>">+ Ajouter</a><a class="btn btn-secondary" href="<?=e_admin_q(Url::to('admin/questions/exclusions'))?>">🔀 Groupes d’exclusion</a><a class="btn btn-secondary" href="<?=e_admin_q(Url::to('admin/questions/import'))?>">Importer CSV</a><a class="btn btn-secondary" href="<?=e_admin_q(Url::to('admin/questions/export'))?>">Exporter CSV</a><a class="btn btn-secondary" href="<?=e_admin_q(Url::to('admin/questions/reference'))?>">Référentiel</a></div></div>
<?php if($message):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#2dd4bf"><?=e_admin_q($message)?></div><?php endif;?><?php if($error):?><div class="card" style="padding:1rem;margin-bottom:1rem;border-color:#fb7185"><?=e_admin_q($error)?></div><?php endif;?>
<section class="card" style="padding:1rem;margin-bottom:1rem"><form method="get" class="grid" style="grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.75rem"><select class="input" name="module_id"><option value="0">Tous les modules</option><?php foreach($modules as $m):?><option value="<?=$m['id']?>" <?=$moduleId===(int)$m['id']?'selected':''?>><?=e_admin_q((string)$m['title'])?></option><?php endforeach;?></select><select class="input" name="category_id"><option value="0">Toutes les catégories</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>" <?=$categoryId===(int)$c['id']?'selected':''?>><?=e_admin_q((string)$c['name'])?></option><?php endforeach;?></select><select class="input" name="type"><option value="">Tous les types</option><?php foreach(['qcm','true_false','multiple','short'] as $t):?><option value="<?=$t?>" <?=$type===$t?'selected':''?>><?=$t?></option><?php endforeach;?></select><select class="input" name="group"><option value="">Tous les groupes</option><?php foreach($groups as $g):?><option value="<?=e_admin_q((string)$g)?>" <?=$group===(string)$g?'selected':''?>><?=e_admin_q((string)$g)?></option><?php endforeach;?></select><select class="input" name="active"><option value="">Tous les états</option><option value="1" <?=$active==='1'?'selected':''?>>Actives</option><option value="0" <?=$active==='0'?'selected':''?>>Inactives</option></select><input class="input" name="q" value="<?=e_admin_q($q)?>" placeholder="Rechercher une question"><button class="btn btn-primary">Filtrer</button><a class="btn btn-secondary" href="<?=e_admin_q(Url::to('admin/questions'))?>">Réinitialiser</a></form></section>
<section class="card table-card">
<div style="padding:1rem;display:flex;justify-content:space-between;align-items:center;gap:1rem;flex-wrap:wrap"><div><strong><?=number_format((int)$totalRows,0,',',' ')?> question(s)</strong><?php if($totalPages>1):?> · page <?=$page?> / <?=$totalPages?><?php endif;?></div><?php if($totalPages>1):?><div style="display:flex;gap:.45rem;align-items:center;flex-wrap:wrap"><?php if($page>1):?><a class="btn btn-secondary" href="<?=e_admin_q(question_page_url(1))?>">« Première</a><a class="btn btn-secondary" href="<?=e_admin_q(question_page_url($page-1))?>">‹ Précédente</a><?php endif;?><?php $start=max(1,$page-2);$end=min($totalPages,$page+2);for($p=$start;$p<=$end;$p++):?><a class="btn <?=$p===$page?'btn-primary':'btn-secondary'?>" href="<?=e_admin_q(question_page_url($p))?>"><?=$p?></a><?php endfor;?><?php if($page<$totalPages):?><a class="btn btn-secondary" href="<?=e_admin_q(question_page_url($page+1))?>">Suivante ›</a><a class="btn btn-secondary" href="<?=e_admin_q(question_page_url($totalPages))?>">Dernière »</a><?php endif;?></div><?php endif;?></div>
<div style="overflow:auto"><table class="table"><thead><tr><th>ID</th><th>Module / catégorie</th><th>Question</th><th>Groupe</th><th>Type</th><th>Niveau</th><th>Réponses</th><th>État</th><th>Actions</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="9">Aucune question.</td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td>#<?=$r['id']?></td><td><small><?=e_admin_q((string)$r['module_title'])?></small><br><strong><?=e_admin_q((string)$r['category_name'])?></strong></td><td><?=nl2br(e_admin_q((string)$r['question']))?><br><small><?=e_admin_q((string)$r['lesson'])?> <?=e_admin_q((string)$r['topic'])?></small></td><td><?=trim((string)($r['exclusion_group']??''))!==''?'<span class="badge">'.e_admin_q((string)$r['exclusion_group']).'</span>':'—'?></td><td><?=e_admin_q((string)$r['type'])?></td><td><?= (int)$r['difficulty']?>/5</td><td><?= (int)$r['answer_count']?></td><td><span class="badge"><?= (int)$r['active']===1?'Active':'Inactive'?></span></td><td style="white-space:nowrap"><a class="btn btn-secondary" href="<?=e_admin_q(Url::to('admin/questions/'.(int)$r['id'].'/edit'))?>">Modifier</a><form method="post" style="display:inline"><input type="hidden" name="csrf_token" value="<?=e_admin_q(Auth::csrfToken())?>"><input type="hidden" name="id" value="<?= (int)$r['id']?>"><button class="btn btn-secondary" name="action" value="duplicate">Dupliquer</button><button class="btn btn-secondary" name="action" value="toggle"><?= (int)$r['active']===1?'Désactiver':'Activer'?></button></form></td></tr><?php endforeach;?></tbody></table></div>
<?php if($totalPages>1):?><div style="padding:1rem;display:flex;justify-content:center;gap:.45rem;align-items:center;flex-wrap:wrap"><?php if($page>1):?><a class="btn btn-secondary" href="<?=e_admin_q(question_page_url($page-1))?>">‹ Précédente</a><?php endif;?><?php $start=max(1,$page-2);$end=min($totalPages,$page+2);for($p=$start;$p<=$end;$p++):?><a class="btn <?=$p===$page?'btn-primary':'btn-secondary'?>" href="<?=e_admin_q(question_page_url($p))?>"><?=$p?></a><?php endfor;?><?php if($page<$totalPages):?><a class="btn btn-secondary" href="<?=e_admin_q(question_page_url($page+1))?>">Suivante ›</a><?php endif;?></div><?php endif;?>
</section>
<?php require dirname(__DIR__).'/_footer.php';?>
